Greeting
AbdelazizSoliman/Hello-Rails-React pull request #1
Opened 2023-10-04 13:16 UTC by AbdelazizSoliman

**Pull request for review create rails-react app using Ruby on Rails, React, and Redux**

- [ ] Create a new Rails app called 'hello-rails-react'.
- [ ] Initialize your project with Git.
- [ ] Set up your project with webpacker the react-rails gems as describe in the previous lesson's tutorial.
- [ ] Make sure that your project has a Postgres database set up.
- [ ] Create a table for storing your messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
- [ ] Create a static view that will be the root of your app.
- [ ] Create the App component with react-router and render it in your static view.
- [ ] Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- [ ] Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

2023-10-04 13:24 UTC, danmainah requested changes
Hi @AbdelazizSoliman , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a pull request summary, has the wrong gitflow, and uses the wrong readme format, kindly use the Microverse readme template when creating your readme.
![image](https://github.com/AbdelazizSoliman/Hello-Rails-React/assets/61408860/59977ba0-f728-42e2-8cda-f93fd1b6bc31)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-04 13:49 UTC, afanimartin requested changes
Hi @AbdelazizSoliman, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't use a professional readme template. Please use [template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-06 00:59 UTC, Shedrack-Sunday requested changes
Hi @AbdelazizSoliman,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 
You have submitted a project, that doesn't use the proper gitflow. Please ensure your branch is pushing to the `dev` branch 👍 

### View:
![image](https://github.com/AbdelazizSoliman/Hello-Rails-React/assets/50990925/f89be52b-e790-4e9a-97d8-991cbeeea74a)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Find me on slack
Martin Afani
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

2023-10-06 01:15 UTC, AbdelazizSoliman commented
Done, I have pushed the dev branch

2023-10-06 02:05 UTC, peterrobert requested changes
Hi @AbdelazizSoliman , 

Very nice project. I love the way you have chosen to use classes for your components. I believe its good to practice using both class and functional components 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️
[ ] Awesome work practicing using classes in your components. I can see you have even attached redux to class components which is different from using redux toolkit. This is a good way to practice using different code bases.✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 02:05 UTC, peterrobert commented on config/routes.rb
> +  root 'api/greetings#random'
- [ ] It will be great to have the root route different from the API route. You should create a route called `root#index`. So you should have a corresponding controller called `root` with one method called `index`.  Also, you should have a corresponding view for this root controller which should have an entry point to your application marked as `<div id="root">`. This is the static view of the application. Kindly check the below requirements ⬇️ 
![Screenshot from 2023-10-06 04-52-12](https://github.com/AbdelazizSoliman/Hello-Rails-React/assets/32361963/957cb5f6-c6b2-456d-94f6-8fc1b3692cdc)

2023-10-06 08:15 UTC, AbdelazizSoliman commented on config/routes.rb
> +  root 'api/greetings#random'
@peterrobert , 
Thank you for helping me how to address my issue. I created the root controller and view and update the routes.

2023-10-06 08:24 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @AbdelazizSoliman 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Index route is properly configured ✔
- Correct use of Git Flow ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 08:38 UTC, AbdelazizSoliman commented
Thank you @AbelG101 for reviewing my PR.

2023-10-06 08:38 UTC, merged